create table if not exists peos_projects (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default now()
);
create table if not exists peos_tasks (
  id bigint generated by default as identity primary key,
  project_id bigint references peos_projects(id) on delete cascade,
  title text not null,
  created_at timestamp with time zone default now()
);
alter table peos_projects enable row level security;
alter table peos_tasks enable row level security;
drop policy if exists "allow_all" on peos_projects;
drop policy if exists "allow_all" on peos_tasks;
create policy "allow_all" on peos_projects for all using (true) with check (true);
create policy "allow_all" on peos_tasks for all using (true) with check (true);
